apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  labels:
    service: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - name: zookeeper-main
      protocol: TCP
      port: 2181
      targetPort: 2181
  type: NodePort