apiVersion: v1
kind: Service
metadata:
  name: kafka-broker2-svc
  labels:
    service: kafka-broker2-svc
spec:
  ports:
  - name: kafka-broker2-svc-port
    targetPort: 9092
    port: 9092
    nodePort: 32402
    protocol: TCP
  - name: kafka-broker2-jmx-port
    targetPort: 7203
    port: 7203
    protocol: TCP
  selector:
    app: kafka-broker2
  type: NodePort