apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-dep-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-1
  template:
    metadata:
      labels:
        app: broker-1
    spec:
      hostname: broker-svc-1
      containers:
      - name: broker-1
        image: foundery.azurecr.io/foundery/kafka/broker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        - containerPort: 7203
        - containerPort: 32401
        env:
        - name: BROKER_ID
          value: "1"
        - name: KAFKA_PORT
          value: "9092"
        - name: EXTERNAL_PORT
          value: "32401"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: INTERNAL_IP
          value: "kafka-broker1-svc"
        - name: ZOOKEEPER_CONNECTION_STRING
          value: "zookeeper-svc-1:2181,zookeeper-svc-2:2181,zookeeper-svc-3:2181"
        - name: JMX_PORT
          value: "7203"
