apiVersion: v1
kind: Service
metadata:
  name: broker-svc-1
  labels:
    service: broker-svc-1
spec:
  ports:
  - name: broker-svc-1-port
    targetPort: 9092
    port: 9092
    nodePort: 32401
    protocol: TCP
  - name: broker-1-jmx-port
    targetPort: 7203
    port: 7203
    protocol: TCP
  selector:
    app: broker-1
  type: NodePort
