apiVersion: v1
kind: Service
metadata:
  name: broker-svc-2
  labels:
    service: broker-svc-2
spec:
  ports:
  - name: broker-svc-2-port
    targetPort: 9092
    port: 9092
    nodePort: 32402
    protocol: TCP
  - name: broker-2-jmx-port
    targetPort: 7203
    port: 7203
    protocol: TCP
  selector:
    app: broker-2
  type: NodePort
