apiVersion: v1
kind: Service
metadata:
  name: kafka-broker1-svc
  labels:
    service: kafka-broker1-svc
spec:
  ports:
  - name: kafka-broker1-svc-port
    targetPort: 9092
    port: 9092
    nodePort: 32401
    protocol: TCP
  - name: kafka-broker1-jmx-port
    targetPort: 7203
    port: 7203
    protocol: TCP
  selector:
    app: kafka-broker1
  type: NodePort