apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-dep-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-2
  template:
    metadata:
      labels:
        app: broker-2
    spec:
      hostname: broker-svc-2
      containers:
      - name: broker-2
        image: spencerschafer/broker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        - containerPort: 7203
        - containerPort: 32402
        env:
        - name: BROKER_ID
          value: "2"
        - name: KAFKA_PORT
          value: "9092"
        - name: EXTERNAL_PORT
          value: "32402"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: INTERNAL_IP
          value: "kafka-broker2-svc"
        - name: ZOOKEEPER_CONNECTION_STRING
          value: "zookeeper-svc-1:2181,zookeeper-svc-2:2181,zookeeper-svc-3:2181"
        - name: JMX_PORT
          value: "7203"
