apiVersion: v1
kind: Service
metadata:
  name: broker-svc-3
  labels:
    service: broker-svc-3
spec:
  ports:
  - name: broker-svc-3-port
    targetPort: 9092
    port: 9092
    nodePort: 32400
    protocol: TCP
  - name: broker-3-jmx-port
    targetPort: 7203
    port: 7203
    protocol: TCP
  selector:
    app: broker-3
  type: NodePort
