apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc-2
  labels:
    service: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - name: zk-client-port-2
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: zk-port-leader-2
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: zk-leader-election-port-2
      protocol: TCP
      port: 3888
      targetPort: 3888
  type: NodePort
