apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc-1
  labels:
    service: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - name: zk-1-client-port
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: zk-1-port-leader
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: zk-1-leader-election-port
      protocol: TCP
      port: 3888
      targetPort: 3888
  type: NodePort
