apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-dep-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-3
        image: spencerschafer/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "3"
      imagePullSecrets:
      - name: dockerprivateregistrykey
